// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentCredits.Microservice.Api.Core.Startup.Context;

#nullable disable

namespace StudentCredits.Microservice.Api.Migrations
{
    [DbContext(typeof(StudentCreditsDbContext))]
    [Migration("20251205014047_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StudentCredits.Microservice.Api.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ana Torres"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carlos Mendoza"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laura Gómez"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jorge Ramírez"
                        },
                        new
                        {
                            Id = 5,
                            Name = "María Fernández"
                        });
                });

            modelBuilder.Entity("StudentCredits.Microservice.Api.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentCredits.Microservice.Api.Entities.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("StudentCredits.Microservice.Api.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 3,
                            Name = "Programación I",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Credits = 3,
                            Name = "Estructuras de Datos",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Credits = 3,
                            Name = "Matemáticas Discretas",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            Credits = 3,
                            Name = "Cálculo Integral",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 5,
                            Credits = 3,
                            Name = "Base de Datos",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 6,
                            Credits = 3,
                            Name = "Arquitectura de Computadores",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 7,
                            Credits = 3,
                            Name = "Ingeniería de Software",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            Credits = 3,
                            Name = "Redes de Computadores",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 9,
                            Credits = 3,
                            Name = "Sistemas Operativos",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            Credits = 3,
                            Name = "Seguridad Informática",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("StudentCredits.Microservice.Api.Entities.StudentSubject", b =>
                {
                    b.HasOne("StudentCredits.Microservice.Api.Entities.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentCredits.Microservice.Api.Entities.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentCredits.Microservice.Api.Entities.Subject", b =>
                {
                    b.HasOne("StudentCredits.Microservice.Api.Entities.Professor", "Professor")
                        .WithMany("Subjects")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("StudentCredits.Microservice.Api.Entities.Professor", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentCredits.Microservice.Api.Entities.Student", b =>
                {
                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("StudentCredits.Microservice.Api.Entities.Subject", b =>
                {
                    b.Navigation("StudentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
